# Generated by Django 4.1.5 on 2023-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
